server:
  port: 8080
  
spring:
  application:
    name: LOAN-MANAGEMENT-SERVICE
    
  datasource:  
    url: jdbc:h2:mem:/loandb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true